import numpy as np
from scipy.stats import multivariate_normal
from abc import ABCMeta


class TransitionModelABC(metaclass=ABCMeta):
    def __call__(self, state_post_prev):
        """Transits `state_post_prev`.

        :param state_post_prev: previous post particles.
        :return: transited particles.
        """
        pass


class ObservationModelABC(metaclass=ABCMeta):
    def __call__(self, state_pre, observation):
        """Resamples `state_pre`.

        :param state_pre: current pre particles.
        :param observation: current observation.
        :return: resampled particles.
        """
        pass


class GaussianTransitionModel(TransitionModelABC):
    def __init__(self, transition_matrix, noise_cov):
        self.transition_matrix = transition_matrix
        self.noise_cov = noise_cov

    def __call__(self, state_post_prev):
        state_post_prev = np.array(state_post_prev)
        n_particles, n_states = state_post_prev.shape
        # assume that noise are generated by multivariate gaussian
        noise = multivariate_normal.rvs(cov=self.noise_cov, size=n_particles)
        noise = noise.reshape(n_particles, n_states)
        state_pre = np.dot(self.transition_matrix, state_post_prev.T).T + noise
        return state_pre


class MonteCarloFilter:
    def __init__(self, n_particles, n_states,
                 particle_initializer=np.random.randn):
        """Creates an instance of `MonteCarloFilter`.

        :param n_particles: the number of particles.
        :param n_states: the number of states.
        :param particle_initializer: particle initializer method.
        """
        assert n_states == 1

        self.n_particles = n_particles
        self.n_states = n_states
        self.particles = particle_initializer(self.n_particles, self.n_states)

        # (n_states, n_states)
        self.transition_model = GaussianTransitionModel(
            np.eye(self.n_states, dtype=np.float32),
            np.eye(self.n_states, dtype=np.float32))

    def predict(self):
        self.state_pre = self.transition_model(self.particles)
        return self.state_pre

    def resample(self, observation, sigma=1.0):
        # random walk: w_k^(i) = h(y_k|x_{k|k}^(i)) = x_{k|k}^(i) + noise
        # TODO: can set observation model
        nll = -multivariate_normal.logpdf(self.state_pre, mean=observation,
                                          cov=sigma)
        # nll = -norm.logpdf(self.state_pre, loc=observation, scale=sigma)
        weights = 1 / nll
        weights /= np.sum(weights)
        # normalize particle weights
        weights /= np.sum(weights)

        # resample
        indices = np.random.choice(self.n_particles, size=self.n_particles,
                                   p=weights)
        self.particles = self.state_pre[indices]
        return self.particles
